# This is a basic workflow to help you get started with Actions

name: Pack QGIS plugin

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
    paths:
      - 'metadata.txt'
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Step 1 - Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        uses: actions/checkout@v3
      
      - name: Step 2 - Set variables
        run: |
          plg_ver=$(sed -nr "/^\[general\]/ { :l /^version[ ]*=/ { s/[^=]*=[ ]*//; p; q;}; n; b l;}" metadata.txt)
          echo "PLUGIN_VERSION=$plg_ver" >> $GITHUB_ENV
      
      - name: Step 3 - Add artifacts to publish to the dist folder
        run: |
          mkdir -p /tmp/SensorThingsAPI/SensorThingsAPI
          rsync -r ./. /tmp/SensorThingsAPI/SensorThingsAPI --exclude .git --exclude .github
          
      - name: Step 4 - Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: SensorThingsAPI.${{ env.PLUGIN_VERSION }}
          path: /tmp/SensorThingsAPI
